import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./Component/header";
import Footer from "./Component/footer";
import Nav from "./Component/nav";
import { UserProvider } from "./context/UserContext"; // Nhập UserProvider

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Bingo NSO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="relative h-full min-h-full">
            <Header />

            <div className="mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl grid grid-cols-12 gap-0 min-h-[calc(100%-var(--header-size)-var(--footer-size))]">
              <div className="xl:col-span-2 md:col-span-3 col-span-12 md:block hidden md:sticky md:top-[var(--header-size)] md:max-h-[calc(100vh-var(--header-size)-var(--footer-size))] md:overflow-y-auto py-4">
                <Nav />
              </div>

              <div className="xl:col-span-10 md:col-span-9 col-span-12 lg:pl-12 md:pl-8">
                <main className="py-4"> {children}</main>
              </div>
            </div>

            <Footer />
          </div>
        </body>
      </html>
    </UserProvider>
  );
}
